In [22]:
import numpy as np
X_independent = np.array(
    [
        [-1, -1], 
        [-2, -1],
        [-3, -2],
        [ 1,  1],
        [ 2,  1],
        [3 ,  2]
    ])

X_dependent = np.array(
    [
        [-1, -1 , -2,-2,0], 
        [-2, -1 , -4,-2,0],
        [-3, -2 , -6,-4,-1],
        [ 1,  1 , 2,2,2],
        [ 2,  1 , 4,2,2],
        [3 ,  2 , 6,4,3]
    ])
Y = np.array([1, 1, 1, 2, 2, 2])
from sklearn.naive_bayes import GaussianNB
clf1 = GaussianNB()
clf1.fit(X_independent, Y)
print(clf1.predict_proba([[-0.8, -1]]))

clf2 = GaussianNB()
clf2.fit(X_dependent, Y)
print(clf2.predict_proba([[-0.8, -1,-1.6,-2,0]]))

[[  9.99999949e-01   5.05653254e-08]]
[[  1.00000000e+00   1.57098733e-20]]


In [23]:
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression()
clf1.fit(X_independent, Y)
print(clf1.predict_proba([[-0.8, -1]]))
clf2 = LogisticRegression()
clf2.fit(X_dependent, Y)
print(clf2.predict_proba([[-0.8, -1,-1.6,-2,0]]))

[[ 0.78807615  0.21192385]]
[[ 0.8896808  0.1103192]]
